### ISSUE TITLE
bug:Highlighting will overwrite the font

### ISSUE THREAD

**Issue by kyle-one** [dracula/logseq#1]
if you use "^^123^^",then yellow highlighting will overwrite the font

**Comment by SlyBouhafs** [comment]
@kyle-one Can you explain a bit more the issue? I don't really understand what you mean!
This is how it looks like on my Logseq:

![Screen Shot 2020-12-22 at 20 06 22](https://user-images.githubusercontent.com/1410462/102924095-2e242700-4491-11eb-9142-da12cd8b633d.png)

**Comment by SlyBouhafs** [comment]
I'll close the issue, feel free to reopen if you wish.
