### ISSUE TITLE
[Feature Request] Progress bar

### ISSUE THREAD

**Issue by kinalmehta** [dracula/logseq#10]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

Thank you for such a great theme.

This is a feature request to add a progress bar for task block based on todo/doing/done 
ref: https://github.com/hisea/logseq-ozean-theme
It'll also be great if instead of using strike once the task is done, just dim it.

I tried going through the CSS but couldn't make sense of it.

Thanks

**Comment by SlyBouhafs** [comment]
Thanks for opening a feature request, the feature has been added!
