### ISSUE TITLE
Calculator Mode results don't line up.

### ISSUE THREAD

**Issue by Ghoughpteighbteau** [dracula/logseq#17]
Start a calculator session with /calculator
<img width="469" alt="image" src="https://user-images.githubusercontent.com/1427632/233495476-d305dbac-957e-4ca3-b3d6-64485dcd787a.png">
the results do not line up.

**Comment by SlyBouhafs** [comment]
Hey @Ghoughpteighbteau Thank for filling the issue and Good job figuring it out! 
If it's not too much trouble, would you consider submitting a pull request to rectify the issue?
