### ISSUE TITLE
Installation from Logseq marketplace outputs [Error]<logseq-dracula-theme> :release-channel-issue "Github API Failed(404) {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/repos#get-the-latest-release\"}"]

### ISSUE THREAD

**Issue by piotrowskiadam** [dracula/logseq#18]
![image](https://user-images.githubusercontent.com/55131509/233506805-2f49aeae-831d-49b1-9585-93f66d65bafb.png)
And it doesn't install
[Error]<logseq-dracula-theme> :release-channel-issue "Github API Failed(404) {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/repos#get-the-latest-release\"}"]

**Comment by jaroet** [comment]
I guess the issue is that there is not a release in the repo? Not very familiair with Github but if 1 of the maintainers could do a release this might work? Thank you.

**Comment by johnnypea** [comment]
I can confirm this, I get the same error.

**Comment by robin-thoene** [comment]
Same here

**Comment by SlyBouhafs** [comment]
Hey folks! I made a new release, can you confirm if the issue is still happening?

**Comment by piotrowskiadam** [comment]
Yup, no issues now. Thanks.

**Comment by robin-thoene** [comment]
Works like a charm, thank you for your work.
