### ISSUE TITLE
pdf阅读页面不显示上方菜单栏

### ISSUE THREAD

**Issue by YangWaldon** [dracula/logseq#4]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.
![image](https://user-images.githubusercontent.com/49675185/141218464-64647a37-84e7-498e-a19a-700911166392.png)

**Comment by SlyBouhafs** [comment]
Closing the issue because the description is unclear. Feel free to open with more details if you the issue happens again.
