### ISSUE TITLE
Todo Checkbox in dark mode are same style with background

### ISSUE THREAD

**Issue by darwis059** [dracula/logseq#5]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

with latest version of logseq, todo checkbox background are same color with background and it makes it invisible

![image](https://user-images.githubusercontent.com/7157397/160953042-c74e4fa1-870f-44f9-9482-62d37ade35b8.png)

**Comment by SlyBouhafs** [comment]
Thanks for reporting the issue!
Which OS are you on? I am using the latest version and as you can see, the todo checkbox is working.
![Screen Shot 2022-04-01 at 14 33 22](https://user-images.githubusercontent.com/1410462/161273820-8ad6ca36-1b60-47e7-a624-c9e43af92c3d.png)
.

**Comment by darwis059** [comment]
I am using windows, logseq 0.6.5

**Comment by hyOzd** [comment]
Same problem here. Linux mint.  0.6.5 nightly 20220408.

**Comment by FieryCod** [comment]
Got the same issue but on the IOS version of LogSeq.

**Comment by SlyBouhafs** [comment]
Really sorry guys for the delay, i haven't had the time to look into the issue, i'll fix once i get some free time.
Meanwhile, if someone has a fix, feel free to send a PR.

**Comment by wensonsmith** [comment]
I have send a PR to fix this issue

macOS & logseq 0.6.6 test ok

**Comment by SlyBouhafs** [comment]
Thanks for the PR @wensonsmith !
I'll leave the issue open for some time to get some feedback, i wasn't able to reproduce the issue on my end so i'm not sure if the fix did work or not!

**Comment by hyOzd** [comment]
@SlyBouhafs Thanks for the fix, it works.
